on:
  push:
    branches:
      - main
      - ZAP-125-deploying-zappy-server-on-server

name: 🚀 Deploy Server on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Compile the files
      run: |
        cmake -S . -B ./build
        cd build
        make -j
        mkdir zappy_server_dir
        mv zappy_server ./zappy_server_dir

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        local-dir: ./build/zappy_server_dir/
        server-dir: /home/matheo/

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: ./targetscript.sh